version: "3"

services:
  database_spring:
    image: mysql:5.6.17
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: spring
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  database_app:
    image: mysql:5.6.17
    ports:
      - "3308:3306"
    volumes:
      - ./src/main/resources/scripts/database/database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: app
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
